[package]
name = "ftlog2"
version = "0.3.2"
edition = "2021"
authors = [ "Non-convex Tech", "Delta4 <delta4chat@gmx.com>" ]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/delta4chat/ftlog"
documentation = "https://docs.rs/ftlog2"
description = """
An asynchronous logging library for high performance
"""
categories = [ "development-tools::debugging" ]
keywords = [ "logging" ]
exclude = [ ".standard-version", ".versionrc", ".github" ]

[features]
default = [ "random_drop" ]
tsc = [ "dep:minstant", "dep:once_cell" ]
random_drop = [ "dep:fastrand" ]

[dependencies]
crossbeam-channel = "0.5.0"
hashbrown = "0.14"
arc-swap = "1"
nohash-hasher = "0.2"
typed-builder = "0.16"

  [dependencies.fastrand]
  version = "2"
  optional = true

  [dependencies.time]
  version = "0.3"
  features = [ "local-offset", "formatting" ]

  [dependencies.minstant]
  version = "0.1"
  optional = true

  [dependencies.once_cell]
  version = "1"
  optional = true

  [dependencies.log]
  version = "0.4"
  features = [ "std", "kv_unstable" ]

[target.'cfg(target_family = "unix")'.dependencies]
tz-rs = { version = "0.6.14" }

